### ISSUE TITLE
这些咋填

### ISSUE THREAD

**Issue by Dason-zdc** [ningjx/OpenTTS#1]
![微信截图_20240226111746](https://github.com/ningjx/OpenTTS/assets/35681112/d1a1fc2c-c595-4000-81bb-6dc97c772030)

**Comment by ningjx** [comment]
可以参照这个视频看看[申请注册微软Azure开通TTS文本转语音服务完整教程](https://www.bilibili.com/video/BV1Ee411C7p5/?vd_source=4a4bc23eb25aef92928881ac444a037e)
或者搜索一下类似“azure 创建语音服务”之类的看看，好像需要有VISA信用卡认证一下才能使用这个服务，不过服务是免费的[官网](https://portal.azure.com/#home)

**Comment by ningjx** [comment]
可以参照这个视频看看[申请注册微软Azure开通TTS文本转语音服务完整教程](https://www.bilibili.com/video/BV1Ee411C7p5/?vd_source=4a4bc23eb25aef92928881ac444a037e)
或者搜索一下类似“azure 创建语音服务”之类的看看，好像需要有VISA信用卡认证一下才能使用这个服务，不过服务是免费的[微软Azure官网](https://portal.azure.com/#home)
